name: Update News

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch and Update News
        run: |

          curl -sL https://news.yahoo.co.jp/rss/topics/top-picks.xml | \
          grep -oE '<title>.*</title>|<link>.*</link>' | \
          sed -e 's/<[^>]*>//g' | \
          tail -n +3 >> news_temp.txt

          mkdir -p NewsTyping
          mv news_temp.txt NewsTyping/news.txt

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add NewsTyping/news.txt
          if ! git diff --staged --quiet; then
            git commit -m "Update news $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
